### ISSUE TITLE
Error : object 'compareDistributions' is not exported by 'namespace:Orcs'

### ISSUE THREAD

**Issue by cstepper** [environmentalinformatics-marburg/Rsenal#4]
Hi Flo, hi Tim,

I tried to build your package locally to provide a binary version for all Windows users in our department. 
Unfortunately, it cannot be built due to the not-exported `Orcs` function `compareDistributions`.

    > devtools::build(binary = TRUE)
    -  installing to library 'C:/Users/christoph.stepper/AppData/Local/Temp/RtmpwJ6XSh/temp_libpath83107694707' (487ms)
    -  installing *source* package 'Rsenal' ...
       ** libs
       make: Nothing to be done for 'all'.
       installing to C:/Users/christoph.stepper/AppData/Local/Temp/RtmpwJ6XSh/temp_libpath83107694707/Rsenal/libs/x64
       ** R
       ** data
       ** inst
       ** byte-compile and prepare package for lazy loading
       Error : object 'compareDistributions' is not exported by 'namespace:Orcs'
       ERROR: lazy loading failed for package 'Rsenal'
    -  removing 'C:/Users/christoph.stepper/AppData/Local/Temp/RtmpwJ6XSh/temp_libpath83107694707/Rsenal'
       In R CMD INSTALL
    Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
      System command error 

I'm not sure, if you're still maintaining any of those two packages, but if so,
it might be worth to include this function to the `Rsenal` package (I couldn't find it in the current `Orcs`).

Thanks, Christoph

**Comment by tim-salabim** [comment]
@fdetsch I think you moved this from Renal to Orcs some time ago right?

**Comment by fdetsch** [comment]
Argh, `compareDistributions()` is currently available from **Orcs** devel, only. I'll submit the updated version to CRAN right after double-checking with winbuilder. Sorry for the inconvenience @cstepper!

**Comment by fdetsch** [comment]
R-winbuilder checks passed, on its way to CRAN.

**Comment by fdetsch** [comment]
> Dear package maintainer,
> 
> this notification has been generated automatically.
> Your package Orcs_1.1.1.tar.gz has been built for Windows and
> will be published within 24 hours in the corresponding CRAN directory.
> R version 3.5.2 (2018-12-20)
> 
> All the best,
> Uwe Ligges
> (Maintainer of binary packages for Windows)

@cstepper Can you please test this once again?

**Comment by cstepper** [comment]
Hi @fdetsch 
just tested if I can build Rsenal:

    > devtools::build(binary = TRUE)
    -  installing to library 'C:/Users/christoph.stepper/AppData/Local/Temp/RtmpgNsWPY/temp_libpath1290791129b0'
    -  installing *source* package 'Rsenal' ...
       ** libs
       C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o Rsenal.dll tmp.def RcppExports.o RsenalCppFun.o -LC:/PROGRA~1/R/R-35~1.2/bin/x64 -lR
       installing to C:/Users/christoph.stepper/AppData/Local/Temp/RtmpgNsWPY/temp_libpath1290791129b0/Rsenal/libs/x64
       ** R
       ** data
       ** inst
       ** byte-compile and prepare package for lazy loading
       ** help
       *** installing help indices
         converting help for package     finding HTML links ...'Rsenal'
        done
           CreateSpacetimeFolds-deprecated         html  
           Rsenal-deprecated                       html  
           Rsenal-package                          html  
           ...
           wdws2uv                                 html  
       ** building package indices
       ** testing if installed package can be loaded
    -  MD5 sums (4.9s)
       packaged installation of 'Rsenal' as Rsenal_0.6.9.zip
    -  DONE (Rsenal)
       In R CMD INSTALL
    [1] "C:/Users/christoph.stepper/Documents/_HOTTY/fromelsewhere/Rsenal_0.6.9.zip"

Everything worked smoothly. 
Thanks for fixing this. 

Best, Christoph
